image: Visual Studio 2017
clone_depth: 10
shallow_clone: true

platform:
    - x64
    - x86

configuration:
#    - Debug
    - Release

environment:
    matrix:
#        - PLATFORM: x86
#          QT_DIR: C:\Qt\5.12.1\msvc2017
        - PLATFORM: x64
          QT_DIR: C:\Qt\5.12.1\msvc2017_64

matrix:
    fast_finish: true
    exclude:
        - platform: x86
          QT_DIR: C:\Qt\5.12.1\msvc2017_64
        - platform: x64
          QT_DIR: C:\Qt\5.12.1\msvc2017

build_script:
    - mkdir build
    - cd build
    - cmake.exe .. "-DCMAKE_PREFIX_PATH=%QT_DIR%" "-DCMAKE_BUILD_TYPE=%CONFIGURATION%" "-DTARGET_ARCH=%PLATFORM%" "-DCMAKE_GENERATOR_PLATFORM=%PLATFORM%"
#    - dir
    - cmake.exe --build . --target winpty
#    - dir thirdparty
    - cmake.exe --build .
    - dir thirdparty\winpty\src\winpty
#    - dir Win32
#    - dir Debug
#    - dir
#    - cmake.exe --build . --target test
#    - dir

#test_script:
#    - ctest -C %CONFIGURATION% --output-on-failure
