image: Visual Studio 2017
clone_depth: 10
shallow_clone: true

platform:
    - x64
    #- x86

configuration:
    - Debug
    #- Release

environment:
    matrix:
        - PLATFORM: x64
          QT_DIR: C:\Qt\5.12.4\msvc2017_64
        #- PLATFORM: x86
        #  QT_DIR: C:\Qt\5.12.1\msvc2017

matrix:
    fast_finish: true
    exclude:
        - platform: x86
          QT_DIR: C:\Qt\5.12.1\msvc2017_64
        - platform: x64
          QT_DIR: C:\Qt\5.12.1\msvc2017

clone_script:
    - git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
    - cd %APPVEYOR_BUILD_FOLDER%
    - git checkout -qf %APPVEYOR_REPO_COMMIT%
    - git submodule update --init --recursive

build_script:
    - dir C:\Qt\
    - mkdir build
    - cd build
    - cmake.exe .. "-DBUILD_SERVER=1" "-DCMAKE_PREFIX_PATH=%QT_DIR%" "-DCMAKE_BUILD_TYPE=%CONFIGURATION%" "-DTARGET_ARCH=%PLATFORM%" "-DCMAKE_GENERATOR_PLATFORM=%PLATFORM%"
    - cmake.exe --build . --target winpty
    - cmake.exe --build .
    - dir thirdparty\winpty\src\winpty

test_script:
    - dir
    - dir tests
    - set PATH=%PATH%;%QT_DIR%\bin
    - cd tests
    - copy winpty-agent.exe Debug\winpty-agent.exe
    - copy winpty.dll Debug\winpty.dll
    #- ptyqt_tests.exe
    #- ctest -C %CONFIGURATION% --output-on-failure
