language: cpp

matrix:
  fast_finish: true
  include:
    - name: Linux
      os: linux
      dist: xenial
      sudo: required
      compiler: gcc
      addons:
        apt:
          packages:
            - qtbase5-dev
            - libqt5websockets5-dev
            - cmake
    - name: OS X (XCode 9.4)
      os: osx
      osx_image: xcode9.4
      compiler: clang
      addons:
        homebrew:
          packages:
            - qt

before_script:
  - #linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ls;
      gcc --version;
      g++ --version;
    fi
  - #osx
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      ls;
    fi
  - #both
  - cmake --version

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cmake . "-DNO_BUILD_EXAMPLES=1";
      cmake --build .;
      cmake --build . --target test;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      ls /usr/local/Cellar/qt/
      cmake . "-DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.11.1";
      cmake --build .;
      cmake --build . --target test;
    fi
